# ======================================
# 网站基础信息配置 - 核心标识参数
# ======================================
title: 明途雁  # 网站在浏览器标签页和搜索引擎显示的主标题
author: 明途雁  # 网站作者信息（用于版权声明和元数据）
subtitle: '无碳能源综合服务'  # 网站副标题（通常显示在标题下方）
description: '无碳能源综合服务'  # 网站内容概述（重要的SEO元素）
language: zh-CN  # 网站语言设置（影响翻译和地区特性）
timezone:  # 网站时区设置（留空使用系统默认时区）

# ======================================
# 网站URL与链接配置 - 路由与美化
# ======================================
url: https://blog.30515245.xyz  # 网站完整域名（用于生成绝对链接）
root: /  # 网站根目录（多站点部署时需修改）
permalink: posts/:abbrlink.html  # 文章永久链接格式（使用abbrlink插件生成短链接）
permalink_defaults:  # 永久链接默认参数（保持空使用Hexo默认）
pretty_urls:  # 美化链接设置（优化SEO和用户体验）
  trailing_index: true  # 是否保留index.html后缀
  trailing_html: true  # 是否保留.html文件后缀
abbrlink:  # abbrlink短链接生成器配置
  alg: crc16   # 算法选择：crc16或crc32（校验和算法）
  rep: dec     # 结果表示：dec(十进制)或hex(十六进制)

# ======================================
# 目录结构配置 - 文件系统组织
# ======================================
source_dir: source  # 原始文件目录（存放Markdown文章和资源）
public_dir: public  # 生成的静态文件目录（用于部署）
tag_dir: tags  # 标签页面存储目录
archive_dir: archives  # 归档页面存储目录
category_dir: categories  # 分类页面存储目录
code_dir: downloads/code  # 代码下载文件存储目录
i18n_dir: :lang  # 多语言文件目录（:lang自动匹配语言）
skip_render:  # 跳过渲染的文件/目录（支持通配符）

# ======================================
# 文章写作配置 - 内容创作规则
# ======================================
new_post_name: :title.md  # 新文章默认文件名格式（:title为标题占位符）
default_layout: post  # 新文章默认布局模板（post/page等）
titlecase: false  # 是否自动将文章标题转为标题格式（首字母大写）
external_link:  # 外部链接打开方式配置
  enable: true  # 是否在新标签页打开外部链接
  field: site  # 应用范围：site(全站)/post(仅文章)
  exclude: ''  # 排除规则（留空不排除任何链接）
filename_case: 0  # 文件名大小写处理：0(保持原样)/1(大写)/2(小写)
render_drafts: false  # 是否渲染草稿文章（front-matter中draft: true的文章）
post_asset_folder: false  # 是否为每篇文章创建独立资源文件夹
relative_link: false  # 是否使用相对链接（多站点部署时使用）
future: false  # 是否显示未来日期的文章
syntax_highlighter: highlight.js  # 代码高亮引擎选择
highlight:  # highlight.js具体配置
  line_number: false  # 是否显示代码行号
  auto_detect: true  # 是否自动检测代码语言
  tab_replace: ''  # 制表符替换字符（用于统一缩进）
  wrap: true  # 是否自动换行
  hljs: true  # 是否使用highlight.js新API
prismjs:  # prismjs高亮引擎备用配置
  preprocess: true  # 是否预处理代码
  line_number: true  # 是否显示行号
  tab_replace: ''  # 制表符替换

# ======================================
# 首页文章列表配置 - 内容展示规则
# ======================================
index_generator:
  path: ''  # 首页路径（留空为根路径）
  per_page: 9 # 每页显示文章数量
  order_by: -date  # 排序规则：-date(降序)/+date(升序)

# ======================================
# 分类与标签配置 - 内容组织系统
# ======================================
default_category: uncategorized  # 文章默认分类
category_map:  # 分类别名映射（key为显示名，value为实际名）
tag_map:  # 标签别名映射（同上）

# ======================================
# 元数据配置 - 搜索引擎优化
# ======================================
meta_generator: true  # 是否在页面中显示Hexo生成器信息

# ======================================
# 日期时间格式配置 - 显示样式
# ======================================
date_format: YYYY-MM-DD  # 日期显示格式（Moment.js格式）
time_format: HH:mm:ss  # 时间显示格式
updated_option: 'mtime'  # 更新时间获取方式：mtime(文件修改时间)/date(文章日期)

# ======================================
# 分页系统配置 - 内容导航
# ======================================
per_page: 9  # 每页文章数量（与index_generator共享配置）
pagination_dir: page  # 分页目录名称（生成page/1.html等）

# ======================================
# 文件包含排除规则 - 构建过程控制
# ======================================
include:  # 强制包含的文件/目录（支持通配符）
exclude:  # 强制排除的文件/目录（优先于.gitignore）
ignore:  # 忽略的文件/目录（类似.gitignore）

# ======================================
# 主题与扩展配置 - 网站外观
# ======================================
theme: butterfly  # 使用的Hexo主题名称（需安装对应主题）

# ======================================
# 部署配置 - 网站发布
# ======================================
deploy:
  type: git  # 部署方式：git/sftp等
  repo: git@github.com:30515245/zhblog.git  # Git仓库地址
  branch: gh-pages  # 部署分支（GitHub Pages专用分支）

# ======================================
# APlayer音乐播放器配置 - 多媒体功能
# ======================================
aplayer:
  meting: true  # 是否启用Meting音乐服务集成
  asset_inject: true  # 是否自动注入播放器资源（手动管理时设为false）