# ======================================
# 基础设置
# ======================================
favicon: /img/favicon.png       # 浏览器标签页小图标路径

avatar:                         # 个人头像设置
  img: https://blogtc.30515245.xyz/20250626215031995.webp  # 头像图片地址
  effect: false                 # 是否启用头像 Hover 特效

nav:                            # 顶部导航栏设置
  logo: https://blogtc.30515245.xyz/20250626215031995.webp  # 导航栏 Logo
  display_title: true           # 是否显示站点名称文字
  fixed: false                  # 导航栏是否固定在顶部

menu:                           # 顶部菜单栏配置： 名称: 路径 || 图标
  首页: / || fas fa-home
  标签: /tags/ || fas fa-tags
  页面||fas fa-book:
    归档: /archives/ || fas fa-archive
    分类: /categories/ || fas fa-folder-open
    图库: /album/ || fas fa-images
    讨论: /shuoshuo/ || fas fa-comment
    友链: /link/ || fas fa-link
  留言板: /message/ || fas fa-comments

# ======================================
# 首页设置
# ======================================
index_layout: 3                 # 首页文章卡片布局样式编号
index_post_content:
  method: 2                     # 摘要获取方式：1=分隔符，2=截取字数
  length: 50                    # 当 method=2 时，摘要最大字数

subtitle:                       # 首页副标题（打字机特效）
  enable: true                  # 是否启用副标题
  effect: true                  # 是否启用打字特效
  loop: true                    # 是否循环播放
  source: 2                     # 动态来源：1/2/3 对应 typed_option.source
  sub:                          # 固定副标题文本列表（当不使用动态接口时）
  typed_option:
    typeSpeed: 40               # 打字速度（ms）
    backSpeed: 20               # 删除速度（ms）
    showCursor: true            # 是否显示光标
    cursorChar: "|"             # 光标字符
    async: true
    source:                     # 动态文本接口
      1: "https://hitokoto.cn/?encode=json"
      2: "https://www.jinrishici.com/all?type=json"
      3: "https://v1.hitokoto.cn/?encode=json"
    strings:
    - "欢迎来到零碳时代"
    - "开启智能与绿色共生之旅"
    - "携手守护地球家园"
    - "探索可再生能源的无限可能"
    - "践行绿色低碳的生活方式"
    - "共创清洁美好的明天"
    - "让每一步都更环保"
    - "用科技驱动绿色未来"
    - "与自然共生，低碳同行"
    - "点亮明天，节能减排"
    - "让地球更绿，让未来更亮"
    - "一起践行碳中和"
# ======================================
# 页面头图与封面设置
# ======================================
disable_top_img: false          # 是否禁用所有页面顶部大图
default_top_img: true           # 是否启用默认顶部大图

# 各页面横幅背景，支持渐变或图片 URL
index_img:      'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
archive_img:    'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
tag_img:        'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
tag_per_img:    'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
category_img:   'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
category_per_img: 'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
footer_img:     'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'

cover:                          # 封面显示开关
  index_enable: true            # 首页封面
  aside_enable: true            # 侧边栏封面
  archives_enable: true         # 归档页封面
  default_cover: 'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'

  # ─── 侧边栏目录（TOC）配置 ───────────────────────────────
toc:
  post: true           # 在文章页显示目录
  page: false          # 在普通页面隐藏目录
  number: false         # 显示每一项的编号
  expand: false        # 默认折叠子节点
  style_simple: false  # 关闭“简洁模式”样式
  scroll_percent: true # 在目录顶部显示阅读进度百分比


# ======================================
# 评论系统配置
# ======================================
comments:
  use: gitalk,valine           # 启用评论系统列表
  text: true                   # 显示“评论”文字提示
  lazyload: false              # 按需加载
  count: false                 # 在文章列表显示评论数
  card_post_count: false       # 在卡片中显示评论数

# ---- Gitalk ----
gitalk:
  client_id: Ov23liJutLKAugcK0j4R
  client_secret: a6963493b9f811bc087ac444559a8db94c2a1453
  repo: pinglen                # 评论数据存储 GitHub 仓库
  owner: 30515245              # 仓库所有者
  admin: 30515245              # 评论管理者
  redirect_uri: https://blog.30515245.xyz  # OAuth 回调

# ---- Valine ----
valine:
  appId: QvInG0iJAXI8Vr3CdLsUwRo5-gzGzoHsz
  appKey: xriETHbw2vAcKhnyCeqYmR9Y
  avatar: monsterid            # 默认访客头像
  visitor: false               # 是否显示访客数

# ======================================
# 外观模式
# ======================================
darkmode:
  enable: true                 # 夜间模式开关
  button: true                 # 显示切换按钮
  autoChangeMode: false        # 是否根据系统时间自动切换

readmode: true                 # 阅读模式开关

# ======================================
# 文章元数据展示
# ======================================
post_meta:
  page:
    date_type: created         # “页面”类型显示创建时间
    date_format: date          # 显示格式：年月日
    categories: true           # 显示分类
    tags: false                # 隐藏标签
    label: true                # 显示标签样式
  post:
    position: left             # 元信息显示在左侧
    date_type: both            # 同时显示创建和更新时间
    date_format: date
    categories: true
    tags: true
    label: true

# ======================================
# 代码块显示
# ======================================
code_blocks:
  theme: light                 # 代码主题：light / dark
  macStyle: false              # 是否启用 Mac 风格窗口按钮
  height_limit: false          # 是否限定高度
  word_wrap: false             # 是否自动换行
  copy: true                   # 显示复制按钮
  language: true               # 显示语言标签
  shrink: false                # 收起按钮
  fullpage: false              # 全页预览

# ======================================
# 侧边栏组件
# ======================================
aside:
  enable: true                 # 启用侧边栏
  position: right              # 位置：left / right
  display:
    archive: true              # 显示归档
    tag: true                  # 显示标签
    category: true             # 显示分类

  card_author:                 # 作者信息卡片
    enable: true
    description: 用绿色改变世界
    button:
      enable: true
      icon: iconfont icon-weixin
      text: 关注我
      link: https://blogtc.30515245.xyz/20250621151601127.webp

  card_announcement:           # 公告卡片
    enable: true
    content: 欢迎来到零碳时代

  card_recent_post:            # 最近文章卡片
    enable: true
    limit: 5
    sort: date

  card_tags:                   # 标签云卡片
    enable: true
    limit: 40
    color: false
    orderby: random
    order: 1

  card_webinfo:                # 站点信息卡片
    enable: true
    post_count: true           # 文章总数
    last_push_date: true       # 最近更新时间

# ======================================
# 404 页面
# ======================================
error_404:
  enable: true
  subtitle: 页面没找到
  background: https://blogtc.30515245.xyz/20250626215031995.webp

# --------------------------------------
# 文章版权声明配置
# --------------------------------------
post_copyright:
  enable: true         # 启用文章版权声明
  decode: false        # 是否对文章 URL 自动解码
  author_href: ""      # 作者链接（留空则不渲染）
  license: "CC BY-NC-SA 4.0"      # 许可证类型
  license_url: "https://creativecommons.org/licenses/by-nc-sa/4.0/"  # 许可证链接


# --------------------------------------
# Word Count 插件配置（需安装 hexo-wordcount）
# --------------------------------------
wordcount:
  enable: false         # 全局开关：启用/禁用插件
  post_wordcount: true  # 在文章 Meta 显示字数统计
  min2read: true        # 在文章 Meta 显示预计阅读时长
  total_wordcount: true # 在侧边栏 WebInfo 显示全站总字数


# ======================================
# 图片灯箱效果
# ======================================
lightbox: medium_zoom          # 可选 fancybox / medium_zoom

# ======================================
# 数学公式渲染
# ======================================
math:
  use: katex                         # 填写 mathjax 或 katex 启用
  per_page: true
  hide_scrollbar: false

  mathjax:
    enableMenu: true
    tags: none

  katex:
    copy_tex: false

# ======================================
# 图片加载错误替换
# ======================================
error_img:
  flink: https://blogtc.30515245.xyz/20250626215031995.webp  # 友链图替换
  post_page: https://blogtc.30515245.xyz/20250626215031995.webp  # 文章页替换

# ======================================
# 打字机爆炸动效
# ======================================
activate_power_mode:
  enable: true
  colorful: true
  shake: true
  mobile: true

# ======================================
# 社交分享
# ======================================
share:
  use: sharejs
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq

# ======================================
# Open Graph & 结构化数据
# ======================================
Open_Graph_meta:
  enable: true
  option: {}

structured_data: true

# ======================================
# 播放器 & 图标字体注入
# ======================================
inject:
  head:                         # 注入到 <head> 的内容
  bottom:
    - '<div class="aplayer no-destroy" data-id="13590986654" data-server="netease" data-type="playlist" data-fixed="true" data-autoplay="true"></div>'
    - '<link rel="stylesheet" href="//at.alicdn.com/t/c/font_4958429_xw3a4lhehsg.css">'

aplayerInject:
  enable: true                  # 启用播放器注入
  per_page: true                # 支持单页控制

# ======================================
# 背景粒子特效（Canvas Nest）
# ======================================
canvas_nest:
  enable: false
  color: '0,0,255'
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false

# ======================================
# 搜索功能配置（支持 Algolia 和本地搜索）
# ======================================
search:
  # 可选值：algolia_search / local_search / docsearch
  # 若不启用搜索则留空
  use: local_search          # 启用本地搜索，请确保安装 searchdb 插件
  placeholder: 搜索一下试试吧～  # 搜索框中的提示占位文字
  # Algolia 搜索配置（未启用可忽略）
  algolia_search:
    hitsPerPage: 6           # 每页返回的搜索结果条数
  # 本地搜索配置（推荐使用 hexo-generator-searchdb 插件）
  local_search:
    preload: true            # 是否在页面加载时预加载搜索索引文件（建议开启）
    top_n_per_article: 6   # 每篇文章最多展示的匹配条数，设为 -1 显示全部匹配
    unescape: true           # 是否对 HTML 转义字符进行解码（可增强可读性）

# ────────────────────────────────────────────
# Mermaid 配置 —— Hexo 全局 _config.yml
# ────────────────────────────────────────────
mermaid:
  # 是否启用 Mermaid 渲染。设为 true，才会处理 {% mermaid %}…{% endmermaid %} 块。
  enable: true

  # 是否把 Markdown 代码块（```mermaid … ```）也当成图表渲染。设为 true 时可两种书写都生效。
  code_write: true

  # 内置主题：default / forest / dark / neutral
  # 这里示例在浅色暗色模式下分别切换
  theme:
    light: default
    dark: dark

  # 注入给 mermaid.initialize() 的全局参数
  config:
    # 自动在 DOMContentLoaded 时渲染
    startOnLoad: true
    # 放宽安全策略，允许内联 HTML 标签（特别是 flowchart.htmlLabels）
    securityLevel: loose
    # 全局字体（可以换成你站点的中英文字体）
    fontFamily: '"Source Han Sans", "Noto Sans", sans-serif'
    # 可选：额外定制整站的 CSS，譬如控制缩放、排版
    themeCSS: |
      .mermaid {
        max-width: 100%;
        margin: 0 auto;
      }
    # 针对 flowchart（流程图）的额外配置
    flowchart:
      useMaxWidth: true     # 图表宽度自适应
      htmlLabels: true      # 使用 HTML 渲染节点（可支持多语言）
    # 针对 sequence diagram（时序图）
    sequence:
      showSequenceNumbers: true
    # 针对 gantt 图
    gantt:
      axisFormat: "%Y-%m-%d"
    # 针对 classDiagram（类图）
    class:
      useMaxWidth: true

  # 是否在渲染时把 config 也内联到页面，方便调试
  inline_config: false
  # 是否生成一个全局的 <script> 标签引入 mermaid，而不是每个图例都单独插
  single_script: true

# ─── 页脚配置 —— 彻底关闭所有展示 ────────────────────
# --------------------------------------
# Footer Settings
# --------------------------------------
footer:
  nav: []              # 如果有导航可在此配置，否则保持空
  owner:
    enable: true       # 显示“站点创建年份”
    since: 2025
  # Copyright of theme and framework
  copyright:
    enable: false       # 显示主题/框架版权
    version: false      # 显示版本号
  # 自定义页脚文本
  custom_text: "绿色能源一站式服务伙伴"

# --------------------------------------
# Busuanzi 访客统计设置
# --------------------------------------
busuanzi:
  site_uv: true    # 全站独立访客数 (UV)
  site_pv: true    # 全站页面浏览量 (PV)
  page_pv: true    # 单页浏览量 (PV)

# --------------------------------------
# Copy 插件配置
# --------------------------------------
copy:
  enable: true          # 全局开关：启用/禁用复制功能
  copyright:
    enable: true       # 复制时是否自动添加版权信息
    limit_count: 150    # 超过 150 字符时才插入版权信息

# ─── 文章分页配置───
post_pagination: 2    # 1: 下一篇指向旧文章；2: 下一篇指向新文章；false: 关闭

# --------------------------------------
# Reward 打赏配置
# --------------------------------------
reward:
  enable: true           # 全局开关：启用/禁用打赏功能
  text: ""               # 打赏说明文字，留空则不显示
  QR_code:               # 二维码列表
    - img: "/img/wechat.jpg"   # 微信二维码图片路径
      link: ""                # 点击二维码后跳转链接（可选）
      text: "微信"             # 支付方式文案
    - img: "/img/alipay.jpg"   # 支付宝二维码图片路径
      link: ""
      text: "支付宝"

# --------------------------------------
# Cloudflare Web Analytics 配置
# https://www.cloudflare.com/zh-tw/web-analytics/
# --------------------------------------
cloudflare_analytics:
  enable: true        # 是否启用 Cloudflare 统计
  token: "be171c5e82a24b278c2200b69bd7c3ae"            # 在 Cloudflare Web Analytics 中申请的 site token

# 页面过渡效果
enter_transitions: true

pwa:
  enable: true
  manifest: /img/pwa/manifest.json
  apple_touch_icon: /img/pwa/apple-touch-icon.png
  favicon_32_32: /img/pwa/32.png
  favicon_16_16: /img/pwa/16.png
  mask_icon: /img/pwa/safari-pinned-tab.svg
