title: 零碳时代  # 网站的标题
author: 零碳时代
subtitle: '绿色能源一站式服务伙伴'  # 网站的副标题
description: '绿色能源一站式服务伙伴'  # 网站的描述信息，用于搜索引擎优化等场景
language: zh-CN  # 网站使用的语言，这里设置为中文（中国大陆）
timezone: # 网站的时区设置，为空表示使用默认时区
# themes/你的主题/_config.yml
url: https://blog.30515245.xyz
root: /
permalink: posts/:abbrlink.html  # 文章永久链接的格式
permalink_defaults:  # 永久链接的默认设置，此处为空表示使用默认值
pretty_urls:  # 美化永久链接的设置
  trailing_index: true  # 设置为 false 可从永久链接中移除尾随的 'index.html'
  trailing_html: true  # 设置为 false 可从永久链接中移除尾随的 '.html'
abbrlink:
  alg: crc16   # 可选 crc16 或 crc32
  rep: dec     # 可选 dec（十进制）或 hex（十六进制）


# Directory  # 目录相关配置的起始注释
source_dir: source  # 源文件目录，存放博客的原始文件，如文章、图片等
public_dir: public  # 生成的静态文件目录，用于部署到服务器
tag_dir: tags  # 标签页面的目录
archive_dir: archives  # 归档页面的目录
category_dir: categories  # 分类页面的目录
code_dir: downloads/code  # 代码文件下载目录
i18n_dir: :lang  # 多语言文件目录，:lang 表示根据语言自动匹配
skip_render:  # 跳过渲染的文件或目录，可在此添加具体规则
# Writing
new_post_name: :title.md  # 新文章的文件名格式
default_layout: post  # 新文章的默认布局
titlecase: false  # 是否将文章标题转换为标题格式
external_link:
  enable: true  # 是否在新标签页中打开外部链接
  field: site  # 外部链接设置应用的范围，这里设置为整个网站
  exclude: ''  # 排除外部链接设置的规则，为空表示不排除
filename_case: 0  # 文件名的大小写处理方式，0 表示保持原样
render_drafts: false  # 是否渲染草稿文章
post_asset_folder: false  # 是否为每篇文章创建对应的资源文件夹
relative_link: false  # 是否使用相对链接
future: false  # 是否显示未来日期的文章
syntax_highlighter: highlight.js  # 代码语法高亮工具，这里设置为 highlight.js
highlight:
  line_number: true  # 是否显示代码行号
  auto_detect: false  # 是否自动检测代码语言
  tab_replace: ''  # 用于替换制表符的内容
  wrap: true  # 是否对代码进行换行处理
  hljs: false  # 是否使用 highlight.js 的新 API
prismjs:
  preprocess: true  # 是否在高亮前对代码进行预处理
  line_number: true  # 是否显示代码行号
  tab_replace: ''  # 用于替换制表符的内容

index_generator:
  path: ''  # 博客首页的根路径
  per_page: 9 # 每页显示的文章数量
  order_by: -date  # 文章排序规则，按日期降序排列

# Category & Tag
default_category: uncategorized  # 文章的默认分类
category_map:  # 分类映射，可用于自定义分类名称
tag_map:  # 标签映射，可用于自定义标签名称

# Metadata elements
meta_generator: true  # 是否在页面中生成 meta 标签的生成器信息

# Date / Time format
date_format: YYYY-MM-DD  # 日期的显示格式
time_format: HH:mm:ss  # 时间的显示格式
updated_option: 'mtime'  # 文章更新时间的选项，这里设置为使用文件修改时间

# Pagination
per_page: 9  # 每页显示的文章数量，用于分页
pagination_dir: page  # 分页目录的名称

# Include / Exclude file(s)
include:  # 需要包含的文件或目录规则，应用于 source 文件夹
exclude:  # 需要排除的文件或目录规则，应用于 source 文件夹
ignore:  # 需要忽略的文件或目录规则

# Extensions
theme: butterfly  # 网站使用的主题


deploy:
  type: git  # 部署方式，这里设置为使用 Git
  repo: git@github.com:30515245/zhblog.git  # 部署的 Git 仓库地址
  branch: gh-pages  # 部署的 Git 分支

aplayer:
  meting: true  # 是否启用 Meting 功能
  asset_inject: false  # 是否自动注入资源

