# ======================================
# 基础设置
# ======================================
favicon: /img/favicon.png       # 浏览器标签页小图标路径

avatar:                         # 个人头像设置
  img: https://blogtc.30515245.xyz/20250612142104764.png  # 头像图片地址
  effect: false                 # 是否启用头像 Hover 特效

nav:                            # 顶部导航栏设置
  logo: https://blogtc.30515245.xyz/20250612142104764.png  # 导航栏 Logo
  display_title: true           # 是否显示站点名称文字
  fixed: false                  # 导航栏是否固定在顶部

menu:                           # 顶部菜单栏配置： 名称: 路径 || 图标
  首页: / || fas fa-home
  标签: /tags/ || fas fa-tags
  页面||fas fa-book:
    归档: /archives/ || fas fa-archive
    分类: /categories/ || fas fa-folder-open
    图库: /album/ || fas fa-images
    讨论: /shuoshuo/ || fas fa-comment
    友链: /link/ || fas fa-link
  留言板: /message/ || fas fa-comments

# ======================================
# 首页设置
# ======================================
index_layout: 3                 # 首页文章卡片布局样式编号
index_post_content:
  method: 2                     # 摘要获取方式：1=分隔符，2=截取字数
  length: 50                    # 当 method=2 时，摘要最大字数

subtitle:                       # 首页副标题（打字机特效）
  enable: true                  # 是否启用副标题
  effect: true                  # 是否启用打字特效
  loop: true                    # 是否循环播放
  source: 1                     # 动态来源：1/2/3 对应 typed_option.source
  sub:                          # 固定副标题文本列表（当不使用动态接口时）
    - "绿色能源一站式服务伙伴"
    - "为可持续发展提供清洁动力"
  typed_option:
    strings:
      - "绿色能源一站式服务伙伴"
      - "为可持续发展提供清洁动力"
    typeSpeed: 40               # 打字速度（ms）
    backSpeed: 20               # 删除速度（ms）
    showCursor: true            # 是否显示光标
    cursorChar: "|"             # 光标字符
    async: true
    source:                     # 动态文本接口
      1: "https://hitokoto.cn/?encode=json"
      2: "https://www.jinrishici.com/all?type=json"
      3: "https://v1.hitokoto.cn/?encode=json"

# ======================================
# 页面头图与封面设置
# ======================================
disable_top_img: false          # 是否禁用所有页面顶部大图
default_top_img: true           # 是否启用默认顶部大图

# 各页面横幅背景，支持渐变或图片 URL
index_img:      'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
archive_img:    'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
tag_img:        'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
tag_per_img:    'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
category_img:   'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
category_per_img: 'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'
footer_img:     'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'

cover:                          # 封面显示开关
  index_enable: true            # 首页封面
  aside_enable: true            # 侧边栏封面
  archives_enable: true         # 归档页封面
  default_cover: 'linear-gradient(135deg, #7BC87B, #4CAF50, #009688)'

# ======================================
# 评论系统配置
# ======================================
comments:
  use: gitalk,valine           # 启用评论系统列表
  text: true                   # 显示“评论”文字提示
  lazyload: false              # 按需加载
  count: false                 # 在文章列表显示评论数
  card_post_count: false       # 在卡片中显示评论数

# ---- Gitalk ----
gitalk:
  client_id: Ov23liJutLKAugcK0j4R
  client_secret: a6963493b9f811bc087ac444559a8db94c2a1453
  repo: pinglen                # 评论数据存储 GitHub 仓库
  owner: 30515245              # 仓库所有者
  admin: 30515245              # 评论管理者
  redirect_uri: https://blog.30515245.xyz  # OAuth 回调

# ---- Valine ----
valine:
  appId: QvInG0iJAXI8Vr3CdLsUwRo5-gzGzoHsz
  appKey: xriETHbw2vAcKhnyCeqYmR9Y
  avatar: monsterid            # 默认访客头像
  visitor: false               # 是否显示访客数

# ======================================
# 外观模式
# ======================================
darkmode:
  enable: true                 # 夜间模式开关
  button: true                 # 显示切换按钮
  autoChangeMode: false        # 是否根据系统时间自动切换

readmode: true                 # 阅读模式开关

# ======================================
# 文章元数据展示
# ======================================
post_meta:
  page:
    date_type: created         # “页面”类型显示创建时间
    date_format: date          # 显示格式：年月日
    categories: true           # 显示分类
    tags: false                # 隐藏标签
    label: true                # 显示标签样式
  post:
    position: left             # 元信息显示在左侧
    date_type: both            # 同时显示创建和更新时间
    date_format: date
    categories: true
    tags: true
    label: true

# ======================================
# 代码块显示
# ======================================
code_blocks:
  theme: light                 # 代码主题：light / dark
  macStyle: false              # 是否启用 Mac 风格窗口按钮
  height_limit: false          # 是否限定高度
  word_wrap: false             # 是否自动换行
  copy: true                   # 显示复制按钮
  language: true               # 显示语言标签
  shrink: false                # 收起按钮
  fullpage: false              # 全页预览

# ======================================
# 侧边栏组件
# ======================================
aside:
  enable: true                 # 启用侧边栏
  position: right              # 位置：left / right
  display:
    archive: true              # 显示归档
    tag: true                  # 显示标签
    category: true             # 显示分类

  card_author:                 # 作者信息卡片
    enable: true
    description: 用绿色改变世界
    button:
      enable: true
      icon: iconfont icon-weixin
      text: 关注我
      link: https://blogtc.30515245.xyz/20250621151601127.webp

  card_announcement:           # 公告卡片
    enable: true
    content: 欢迎来到零碳时代

  card_recent_post:            # 最近文章卡片
    enable: true
    limit: 5
    sort: date

  card_tags:                   # 标签云卡片
    enable: true
    limit: 40
    color: false
    orderby: random
    order: 1

  card_webinfo:                # 站点信息卡片
    enable: true
    post_count: true           # 文章总数
    last_push_date: true       # 最近更新时间

# ======================================
# 404 页面
# ======================================
error_404:
  enable: true
  subtitle: 页面没找到
  background: https://blogtc.30515245.xyz/20250613104116053.png

# ======================================
# 文章版权声明
# ======================================
post_copyright:
  enable: true
  author_href: https://blogtc.30515245.xyz/
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# ======================================
# 字数统计与阅读时长
# ======================================
wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# ======================================
# 图片灯箱效果
# ======================================
lightbox: medium_zoom          # 可选 fancybox / medium_zoom

# ======================================
# 数学公式渲染
# ======================================
math:
  use: katex                         # 填写 mathjax 或 katex 启用
  per_page: true
  hide_scrollbar: false

  mathjax:
    enableMenu: true
    tags: none

  katex:
    copy_tex: false

# ======================================
# 图片加载错误替换
# ======================================
error_img:
  flink: https://blogtc.30515245.xyz/20250613104116053.png  # 友链图替换
  post_page: https://blogtc.30515245.xyz/20250613104116053.png  # 文章页替换

# ======================================
# 打字机爆炸动效
# ======================================
activate_power_mode:
  enable: true
  colorful: true
  shake: true
  mobile: true

# ======================================
# 社交分享
# ======================================
share:
  use: sharejs
  sharejs:
    sites: facebook,twitter,wechat,weibo,qq

# ======================================
# Open Graph & 结构化数据
# ======================================
Open_Graph_meta:
  enable: true
  option: {}

structured_data: true

# ======================================
# 播放器 & 图标字体注入
# ======================================
inject:
  head:                         # 注入到 <head> 的内容
  bottom:
    - '<div class="aplayer no-destroy" data-id="13590986654" data-server="netease" data-type="playlist" data-fixed="true" data-autoplay="true"></div>'
    - '<link rel="stylesheet" href="//at.alicdn.com/t/c/font_4958429_xw3a4lhehsg.css">'

aplayerInject:
  enable: true                  # 启用播放器注入
  per_page: true                # 支持单页控制

# ======================================
# 背景粒子特效（Canvas Nest）
# ======================================
canvas_nest:
  enable: false
  color: '0,0,255'
  opacity: 0.7
  zIndex: -1
  count: 99
  mobile: false
